# Generated by Django 2.2.5 on 2019-09-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baiviet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieude', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('noidung', models.TextField(verbose_name='Nội dung')),
            ],
        ),
        migrations.CreateModel(
            name='Sanpham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensanpham', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('hinhanh', models.ImageField(upload_to='sanpham/', verbose_name='Hình ảnh')),
                ('giatien', models.CharField(max_length=50, verbose_name='Giá tiền')),
                ('noidung_gioithieu', models.TextField(verbose_name='Nội dung giới thiệu')),
                ('ngaycapnhat', models.DateTimeField(verbose_name='Ngày cập nhật')),
                ('nguoicapnhat', models.CharField(max_length=200, verbose_name='Người cập nhật')),
            ],
        ),
    ]
