# Generated by Django 2.2.5 on 2019-09-16 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danhmuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendanhmuc', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('gioithieu', models.CharField(max_length=200, verbose_name='Giới thiệu')),
                ('slug', models.CharField(default=1, max_length=200, verbose_name='Đường dẫn slug')),
            ],
            options={
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.AddField(
            model_name='baiviet',
            name='danhmuc',
            field=models.CharField(default='None', max_length=200, verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='ngaycapnhat',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='ngayvietbai',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày viết bài'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baiviet',
            name='nguoiviet',
            field=models.CharField(default='None', max_length=50, verbose_name='Người viết bài'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='ngaycapnhat',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
    ]
