# Generated by Django 2.2.5 on 2019-09-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0002_auto_20190916_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baiviet',
            options={'verbose_name_plural': 'Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='sanpham',
            options={'verbose_name_plural': 'Sản phẩm'},
        ),
    ]
